### ISSUE TITLE
version GLIBC_2.29 not found

### ISSUE THREAD

**Issue by maackle** [holochain/launcher-tauri#1]
Even after installing the extra packages mentioned in the releases, I get the following error when trying to run the launcher.

```
$ ./holochain-launcher_0.0.1_amd64.AppImage
holochain-launcher: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by holochain-launcher)
```

I suppose I could build and install glibc-2.29 from source, but it would be nice if the launcher could be run only with help from a package manager

**Comment by guillemcordoba** [comment]
Thanks @maackle. Which OS are you using?

**Comment by maackle** [comment]
Linux Mint 19.2 Cinnamon

**Comment by guillemcordoba** [comment]
@maackle can you confirm that the error is gone with this new release? https://github.com/holochain/launcher/releases/download/untagged-936b0825667921808acc/holochain-launcher_0.2.0-alpha.1_amd64.AppImage

**Comment by maackle** [comment]
@guillemcordoba the link doesn't work, and I don't see a 0.2.0-alpha.1 release

**Comment by guillemcordoba** [comment]
Oh sorry, okey so it seems release drafts are private and they don't even have links working. I'll publish the release and ping you about it.

**Comment by guillemcordoba** [comment]
@maackle can you confirm now with https://github.com/holochain/launcher/releases/tag/v0.2.0?

**Comment by maackle** [comment]
@guillemcordoba I'm able to run this version!

**Comment by guillemcordoba** [comment]
Seeing this again with launcher v0.3.0

**Comment by guillemcordoba** [comment]
@gabmmontenegro can you confirm that [0.3.1](https://github.com/holochain/launcher/releases/tag/v0.3.1) fixes this issue?

**Comment by gabmmontenegro** [comment]
@guillemcordoba fixed. Thank you!
