### ISSUE TITLE
Elemental Chess just 'spins' after launch

### ISSUE THREAD

**Issue by davewolf99** [holochain/launcher-tauri#11]
When I open elemental chess from the Holochain launcher, it opens a browser window with localhost and a port in the address bar, but just continues to show a 'loading' indicator in the screen. I didn't specifically time it, but was probably around 2-3 minutes before I closed out. Tried uninstalling the hApp and reinstalling. No change in behavior. 

- Used the links provided by Guillem in Devcamp8 Discord to install on Windows 10.
- Elemental chat opens fine.
- entered 'devcamp' as UID for both chat and chess

----------
Windows 10 Home Version 20H2

Holochain Launcher v0.3.0
Holochain v0.0.107
Lair Keystore v0.0.4

----------

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
Please attach here the `launcher.log` file. To find it, go to `Holochain Admin` window of the Holochain Launcher, select the  `Settings` menu, and select `Open Logs`. Attach that file to this issue.

> In Ubuntu, there is a weird error that prevents the upload of a file from inside a hidden folder. To work around it, you can copy the `launcher.log` file to another non-hidden location, and upload it from there.

**Screenshots*
[launcher.log](https://github.com/holochain/launcher/files/7245411/launcher.log)
*

**Desktop (please complete the following information):**
 - OS: [e.g. MacOs v10.13]
 - Holochain Launcher Version [e.g. 0.], you can find out in `Help` > 'About'

**Additional context**

**Comment by guillemcordoba** [comment]
Thanks so much :)

**Comment by davewolf99** [comment]
IDK what the difference is, but I just tried launching it again a few minutes ago and it opened just fine within about a second. I was able to enter a nickname and I see the interface. Haven't tried playing a game yet though

**Comment by guillemcordoba** [comment]
I'm going to close this as it was a bug with a previous version of Elemental-Chess, not Launcher related. Re-open if it shows up again.
