### ISSUE TITLE
Version numbers for hApp and for UI should appear in the more-info section

### ISSUE THREAD

**Issue by zippy** [holochain/launcher-tauri#112]
**Is your feature request related to a problem? Please describe.**
I was just trying debug stuff regarding a UI, and there was no way to tell which version of the UI got installed.

**Describe the solution you'd like**
When you turn down the ... there should be a section that gives the hApp version info, and the GUI version info that was pulled from DevHub/AppStore

**Comment by matthme** [comment]
Fixed with ece4fc1cdb9a409672b19c308706827d63901b21
