### ISSUE TITLE
UX Tweak: Change the clickable target for adding 'advanced' details

### ISSUE THREAD

**Issue by Connoropolous** [holochain/launcher-tauri#113]
Currently you can only click the `+`, but I think you should be able to click the word 'advanced' as well, and have it expand/collapse

<img width="461" alt="Screenshot 2023-01-09 at 1 03 43 PM" src="https://user-images.githubusercontent.com/1409121/211408239-fc35d64e-5cfa-4e46-81cb-5f43b83c9a36.png">

**Comment by matthme** [comment]
Agreed. I'm gonna change that
