### ISSUE TITLE
change dialog-open to dialog-all in tauri feature

### ISSUE THREAD

**Issue by weswalla** [holochain/launcher-tauri#116]
https://github.com/holochain/launcher/blob/74aeb0e61304205d5445ba9bf4ee7e9d39129b72/crates/hc_launch/src-tauri/Cargo.toml#L49

fails to compile unless you change `dialog-open` to `dialog-all` to match what's in `tauri.conf.json`

**Comment by matthme** [comment]
Thanks! Already came across this myself so I added that recently: https://github.com/holochain/launcher/blob/efbf1e23d696f2f645033cdf47b3578f81140eb3/src-tauri/tauri.conf.json#L66

**Comment by weswalla** [comment]
trying to run `cargo install holochain_cli_launch --git https://github.com/holochain/launcher.git` gave this error, so I cloned the repo locally and changed `dialog-open` in https://github.com/holochain/launcher/blob/74aeb0e61304205d5445ba9bf4ee7e9d39129b72/crates/hc_launch/src-tauri/Cargo.toml#L49 to `dialog-all` and it fixed the compile error
```
error: failed to run custom build command for `holochain_cli_launch v0.0.5 (/Users/weswalla/lrl/launcher/crates/hc_launch/src-tauri)`

Caused by:
  process didn't exit successfully: `/Users/weswalla/lrl/launcher/target/release/build/holochain_cli_launch-e9d386a9f4f96416/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop

        The `tauri` dependency features on the `Cargo.toml` file does not match the allowlist defined under `tauri.conf.json`.
        Please run `tauri dev` or `tauri build` or remove the `dialog-open` feature and add the `dialog-all` feature.
```

**Comment by matthme** [comment]
Yes, you're right, I had the wrong thing in mind. I fixed that as well today: https://github.com/holochain/launcher/blob/2724dd716d84414a57ef7f419f937695cbda0f70/crates/hc_launch/src-tauri/Cargo.toml#L50 but not merged into develop yet.
