### ISSUE TITLE
Blank home page when launched

### ISSUE THREAD

**Issue by hanksohota** [holochain/launcher-tauri#12]
**Describe the bug**
'Blank' home page.
App title bar: 'Holochain Admin'
Menu bar: 'Settings'; 'Help' (both work fine)
No 'Installed Apps' page title or '+ INSTALL NEW APP' purple button.

**To Reproduce**
Run AppImage file (with execution permission).

**Expected behavior**
Home page with 'Installed Apps" title and '+ INSTALL NEW APP' button.

**Logs**
Please attach here the `launcher.log` file. To find it, go to `Holochain Admin` window of the Holochain Launcher, select the  `Settings` menu, and select `Open Logs`. Attach that file to this issue.

> In Ubuntu, there is a weird error that prevents the upload of a file from inside a hidden folder. To work around it, you can copy the `launcher.log` file to another non-hidden location, and upload it from there.

**Screenshots**
If applicable, add screenshots to help explain your problem
[launcher.log](https://github.com/holochain/launcher/files/7251806/launcher.log)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS 
 - Holochain Launcher Version 0.3.0

**Additional context**

**Comment by guillemcordoba** [comment]
@hanksohota thanks :) 

Can you confirm that [0.3.1](https://github.com/holochain/launcher/releases/tag/v0.3.1) fixes this issue?

**Comment by hanksohota** [comment]
Yes, everything seems to be working fine as far as I can tell :~)

So excited!

Thanks.
