### ISSUE TITLE
Rea-playspace

### ISSUE THREAD

**Issue by Stormn12** [holochain/launcher-tauri#129]
First attempt to open any app. Goes to rea-playspace screen with 'Loading . . .' for 8 to 10 hours with no change.

**Comment by matthme** [comment]
Hi @Stormn12 . I would need some more context to be able to understand the issue. What Launcher version are you running and what version of rea-playspace are you running? It's for example possible that there is an incompatibility between holochain versions.
Also it might help if you'd "right-click > Inspect element" and then check whether you see any errors under the  "Console" tab.

**Comment by Stormn12** [comment]
Matthme,

I use Windows 10 on my laptop. Sometimes I have to reboot my computer in order to successfully relaunch the HoloLauncher.

Holo Launcher V0.8.0 (newest)
ReaPlaySpace V0.0.18 (newest)

See 2 attachments of Inspect Element / Console

Norm

     On Wednesday, February 8, 2023, 06:45:45 AM MST, matthme ***@***.***> wrote:  
 
 


Hi @Stormn12 . I would need some more context to be able to understand the issue. What Launcher version are you running and what version of rea-playspace are you running? It's for example possible that there is an incompatibility between holochain versions.
Also it might help if you'd "right-click > Inspect element" and then check whether you see any errors under the "Console" tab of that section that should pop up.

**Comment by matthme** [comment]
Thanks for the details! I had a look at it now and I saw that rea-playspace from this release is using an older holochain version (before beta release). Holochain had quite a few breaking changes around beta release so I suspect that's the problem. A new launcher with the official Holochain Beta version is going to come out really soon and maybe they will also publish a new rea-playspace release for that Holochain version soon after.
