### ISSUE TITLE
Update official hApp UI without re-installing happ

### ISSUE THREAD

**Issue by mattyg** [holochain/launcher-tauri#132]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to update to the latest version of a hApp's "official" UI without re-installing it.

**Describe the solution you'd like**
Roughly I'm imagining:
- a button displayed under a hApp in the launcher that says: "Update UI to 0.0.X"
- a launcher setting that lets the user choose to "auto-update official UIs"
- If auto-updating of UIs is enabled, the launcher checks all installed happs for available UI updates on a recurring schedule (say daily).

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by matthme** [comment]
That's already possible actually, at least it should be if there's no bug. Provided that you add the new official UI to the same happ release as the prior one in the DevHub. An "Update" button should appear on the app and allow you to update to the latest UI. It just currently requires a page refresh for the button to appear.

**Comment by mattyg** [comment]
> That's already possible actually, at least it should be if there's no bug. Provided that you add the new official UI to the same happ release as the prior one in the DevHub. An "Update" button should appear on the app and allow you to update to the latest UI. It just currently requires a page refresh for the button to appear.

~Do you mean I'm supposed to just set the "Official UI" for a prior release to the latest uploaded UI? I don't think there's a way to upload a new UI without creating a new release as well.~

Still I can't seem to get the update button to show. I tried replacing all the "Official UI" for all prior releases with the latest UI. I also tried using integer version numbers in case it was an issue with 0.0.X version comparison.

Not sure if this is a devhub or launcher issue.

**Comment by matthme** [comment]
Did you try the steps in this section: https://github.com/holochain/launcher#updating-the-ui-of-your-web-app ?

**Comment by mattyg** [comment]
> Did you try the steps in this section: https://github.com/holochain/launcher#updating-the-ui-of-your-web-app ?

Okay, I just tried uploading the new ui zip file via "My GUIs", and then assigned all releases of the happ to that latest GUI. Still not seeing the latest UI nor an update button after restarting launcher. I assume I don't have to wait for network validation, do I?

**Comment by matthme** [comment]
No you shouldn't. Since you uploaded it yourself the data should also already be there. One reason it might not be working is that you did not install the app via the app library but from the filesystem. Because in that case the launcher cannot relate it to a happ release hash in the DevHub.
You can check whether you have the following files (assuming you are on Linux):
`~/.local/share/holochain-launcher/profiles/default/holochain/0.1/apps/[name of your app]/uis/default/.guirelease`
and
`~/.local/share/holochain-launcher/profiles/default/holochain/0.1/apps/[name of your app]/.happrelease`
Those are the files the launcher takes to check for available updates.

**Comment by matthme** [comment]
If that's not the problem it may potentially also be related to https://github.com/holochain/launcher/issues/133 but I'd need to look into this in more depth...

**Comment by mattyg** [comment]
> No you shouldn't. Since you uploaded it yourself the data should also already be there. One reason it might not be working is that you did not install the app via the app library but from the filesystem. Because in that case the launcher cannot relate it to a happ release hash in the DevHub. You can check whether you have the following files (assuming you are on Linux): `~/.local/share/holochain-launcher/profiles/default/holochain/0.1/apps/[name of your app]/uis/default/.guirelease` and `~/.local/share/holochain-launcher/profiles/default/holochain/0.1/apps/[name of your app]/.happrelease` Those are the files the launcher takes to check for available updates.

Yes got it! Sorry about this, my mistake: the app was installed from a local file. Thanks so much for your help!
