### ISSUE TITLE
Display hApp version & ui version of installed apps

### ISSUE THREAD

**Issue by mattyg** [holochain/launcher-tauri#134]
**Is your feature request related to a problem? Please describe.**
Sorry for the barrage of tickets! Just a small request: I'd love to be able to view the app & ui version of currently installed hApps.

**Describe the solution you'd like**
- Display each hApps installed hApp version and UI version in the 'App Details' area, above or below the 'Holochain Version'
- Display "Installed from Local File" if not installed from devhub (or vice versa)

**Comment by matthme** [comment]
Yes that's probably a good idea. I'm hesitant to implement it right now because it requires storing that information on the file system upon installation and that logic may change as soon as the app store is integrated as a layer between DevHub and Launcher so it would be duplicated effort.

**Comment by matthme** [comment]
Has been implemented as part of recent releases.
