### ISSUE TITLE
Delete failed

### ISSUE THREAD

**Issue by WeSeeInside** [holochain/launcher-tauri#138]
I spent the day with Holochain at the Posner during ETHDenver.
I need to delete all holochain files from terminal and hard drive.  
I tried > rm - rf junk
remove - recursive force 
the response was " junk file not found "  I tried it without junk.  still no response or action noted.
how should I proceed to reach the goal of removing holochain files from hard drive?

**Comment by matthme** [comment]
If you want to irrevocably delete all files related to the Holochain Launcher you can do so by deleting all the folders listed here: https://github.com/holochain/launcher/#data-storage, depending on your operating system.

In case you're on Linux, the following 2 commands should do the trick:
```
rm -rf ~/.local/share/holochain-launcher
rm -rf ~/.config/holochain-launcher
```
