### ISSUE TITLE
web apps reverting to prior versions of coordinator zomes upon restarting launcher

### ISSUE THREAD

**Issue by mattyg** [holochain/launcher-tauri#150]
**Describe the bug**
Okay this is very weird bug, and I don't have a minimal reproduction yet, but I will try to create one. 

**How I reproduced it**
- Installed an older version of herddit (this was a month ago, using 0.9.0 launcher)
- Installed the latest version of herddit that includes coordinator zome updates
- Start latest version of herddit
(works as expected)
- Restart launcher
- Start latest version of herddit
(does not work as expected: errors indicate that it is calling coordinator zomes from the prior version)

**attempts to fix**
- disabled old versions of hApp (no change)
- deleting old version of hApp (no change)
- unpublished all prior versions on devhub (no change)
- published latest version as a separate web-app on devhub (no change)
- factory resetting launcher (resolved the issue)

**To Reproduce**
(coming soon)

**Expected behavior**
hApps should behave the same upon first install as after launcher restart

**Logs**
Mine is 2gb, let me know if you need it.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [e.g. MacOs v10.13]: Ubuntu 22.04
 - Holochain Launcher Version: 0.9.3

**Additional context**
n/a

**Comment by matthme** [comment]
Can I ask a few more questions:
- Was the old version of herddit still installed while you got the errors in the new version (I think yes from reading your fix attempts but just to make sure)?
- if no, was the installed app id of the new version the same or different than the one of the old version (maybe there were some weird left-overs in the conductor for this app id?)
- how do you infer exactly that it's using old coordinator zomes? What kind of error do you get?

**Comment by mattyg** [comment]
> * Was the old version of herddit still installed while you got the errors in the new version (I think yes from reading your fix attempts but just to make sure)?

At first yes. Then I tried disabling the old version and was still able to reproduce. Then I tried deleting the old version and was still able to reproduce

> 
>     * if no, was the installed app id of the new version the same or different than the one of the old version (maybe there were some weird left-overs in the conductor for this app id?)

Hmmm, I'm pretty sure I used different installed app ids every time. It's possible I may have used one of those app ids in the past, and then since deleted the happ.

> 
>     * how do you infer exactly that it's using old coordinator zomes? What kind of error do you get?

The coordinator zome update changed a zome call's response type. By logging the zome call response I saw that it was receiving the previously used response type.

**Comment by matthme** [comment]
Hmm...okay. At the moment I don't see how the Launcher could affect anything regarding coordinator zomes because it currently always installs apps as a whole, no separate handling of coordinator zomes whatsoever (the feature of upgrading/changing coordinator zomes might be added at some point). So currently I would rather locate the bug in holochain. Two things that I can imagine:
* holochain routed the call to the wrong cell since they (presumably) have the same DNA hash but different agent public keys.
* As you said you may possibly have used the same app id earlier with an earlier version of herddit. So maybe there might be a bug that coordinator zomes had not been properly removed upon uninstalling.

**Comment by mattyg** [comment]
okay I'll see if I can make a minimal reproduction. thanks!

**Comment by matthme** [comment]
That would be great!
Thinking about it, there may actually be potential failure cases of the Launcher in that it might connect UIs to the wrong cell for some reason.

**Comment by mattyg** [comment]
Okay, got a working reproduction. It's not related to using the same app id. No idea if it indicates a launcher or holochain issue, but I figure you'll know better than me.

See the README for steps to reproduce: https://github.com/mattyg/bug-reproduction-cell-routing

**Comment by matthme** [comment]
Wow, thanks a lot for this reproduction! I will have a look whether I can identify or at least narrow down the issue.
