### ISSUE TITLE
Installation on Win 10 running into Keystore VCRuntime Error

### ISSUE THREAD

**Issue by joatu** [holochain/launcher-tauri#151]
![win 10 lair keystore bug](https://user-images.githubusercontent.com/5350076/227798680-b02de9ff-a751-4aa2-a45d-9970d4a885f6.png)

A dutch friend was trying to install the latest version on his Win 10 machine. He uninstalled the earlier versions and restarted his machine. Continued to come across the same error message regarding VCRuntime140.dll error.

**Comment by matthme** [comment]
Hi @joatu thanks for the report! This seems to be a somewhat known issue with Windows 10, here's a blog post describing possible solutions to solve it: https://www.winhelponline.com/blog/fix-vcruntime140-dll-missing-error-windows/

Let me know whether your friend is able to fix it following these instructions.

**Comment by DaYaLaLa** [comment]
Option 3: Download Visual C++ Redistributable from MS Download Center
If the problem persists even after repairing it, you may try downloading the Microsoft Visual C++ Redistributable from the Microsoft Download Center. Download and install both the x86 and x64 versions of the Visual C++ redistributable package:

MS Visual C++ Redistributable for Visual Studio 2015-19, or 2022
x86 (32-bit): [vc_redist.x86.exe](https://aka.ms/vs/17/release/vc_redist.x86.exe)
x64 (64-bit): [vc_redist.x64.exe](https://aka.ms/vs/17/release/vc_redist.x64.exe)


was meteen successful for me

**Comment by matthme** [comment]
Fabulous, thank you for sharing!
