### ISSUE TITLE
Windows 10 freeze when installation of version 0.9.3 

### ISSUE THREAD

**Issue by ambiprospect** [holochain/launcher-tauri#152]
Cannot launch the latest version.
![Launcher uppload 230327](https://user-images.githubusercontent.com/17433213/228017367-5dfa0e62-49f3-4801-a18a-d636e0250324.png)

**Comment by matthme** [comment]
Thank you for the report! Can you tell me a bit more about what happens exactly? I test each Launcher release myself on a Windows 10 Laptop and didn't experience any major problems yet so it's hard to infer what might be the issue.

What do you mean by "Windows 10 freeze"? What freezes, your PC as a whole or just the Launcher? And does the Launcher start up at all or when does the issue occur exactly?

p.s. there is another release out now (0.9.4) that you could try instead, although I don't think there were significant changes that would affect the problem you're describing.

**Comment by ambiprospect** [comment]
When I click on **Install** there is a square for a short while. then the screen will be black, with the exception of some short blinks of light and after some seconds the screen will be totally black, and you can not do anything on the PC. Even if I waited a long period of time, nothing happened. To release the PC I have to switch it off by pressing the start key until the PC will be silent. I remember  I had similar problem the first time  I uploaded Launcher version 0.8.0 but then I succeeded at last, but not this time. 
To check on my side I will try if the same happens with a second ASUS-laptop I have.

**Comment by ambiprospect** [comment]
The test with the ASUS laptop say (in Swedish).
"Installationspaketet stöds inte av den här processortypen. Kontakta återförsäljaren av maskinvaran"
"The installation package is not supported by this processor type. Contact your hardware dealer"
Processor: Intel(R) Atom(TM) CPU Z3740 @1,33 GHz

**Comment by ambiprospect** [comment]
Will also test with my wife's  Lenovo desktop.

**Comment by ambiprospect** [comment]
Success! Tried version 0.9.4 on Folke-PC and there is no problem any longer.

**Comment by matthme** [comment]
Glad to hear! Still a bit weird though that this black screen issue occured... I'll close the issue for now but if it occurs again, feel free to report back here.
