### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by tansnowman** [holochain/launcher-tauri#17]
On Mac OS 11.5.2, After clicking the open button in the Holochain Launcher (0.3.2), I get redirected to Firefox, with the following message:

Unable to connect

Firefox can’t establish a connection to the server at localhost:24236.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

<img width="838" alt="Screen Shot 2021-10-01 at 8 34 32 AM" src="https://user-images.githubusercontent.com/83926039/135639351-71b4baa0-29b7-47e2-942d-993fe5abc9b7.png">

**Comment by sarbazx** [comment]
same on MacOS 11.6 M1

**Comment by shanedeeodonnell** [comment]
Same on MacOs 10.15 intel

Last few lines of the log
`[2021-10-05T22:15:31.708955-04:00] INFO - [HOLOCHAIN] [2mOct 05 22:15:31.708[0m [33m WARN[0m holochain::core::workflow::app_validation_workflow: agent=uhCAka1cpyNTlxXWmYGLRh68K8_dAENBYRo3p-aRcxZfI8znROj1B msg="DhtOp has failed app validation" outcome=AwaitingDeps([AnyDhtHash(uhCEkCrNJ-geNtzZu9ySiBEN5YU5YuDfiOScFJvnLZCmu5MlBDRlX)])
[2021-10-05T22:15:32.020851-04:00] INFO - [HOLOCHAIN] [2mOct 05 22:15:32.020[0m [33m WARN[0m holochain::core::workflow::app_validation_workflow: agent=uhCAka1cpyNTlxXWmYGLRh68K8_dAENBYRo3p-aRcxZfI8znROj1B msg="DhtOp has failed app validation" outcome=AwaitingDeps([AnyDhtHash(uhCEkaDd6kdHxasGFx_5cSTAF6P3eZtLrjOsvnDaJoKNdHPHucyGa)])
[2021-10-05T22:18:56.762757-04:00] INFO - [UI] Installed app
[2021-10-05T22:18:56.763618-04:00] INFO - Opening app elemental-chess at http://localhost:21036, result: Ok(())`

Even though the last line suggest things are OK, the original issue persists.

**Comment by guillemcordoba** [comment]
Thanks @tansnowman  , can you confirm that this is solved with [Launcher 0.3.3](https://github.com/holochain/launcher/releases/tag/v0.3.3)?

**Comment by shanedeeodonnell** [comment]
@guillemcordoba 0.3.3 is working for me now.

**Comment by tansnowman** [comment]
I was able to connect, and played my first game two days ago. Worked great!
