### ISSUE TITLE
Launcher icon is fuzzy

### ISSUE THREAD

**Issue by TechSupport26** [holochain/launcher-tauri#178]
**Describe the bug**
When I run the launcher the icon in both my application bars are fuzzy. 
I am using the Latte Dock and the application menu bar.

**Screenshots**
![image](https://github.com/holochain/launcher/assets/65631811/1191c8e7-127a-4224-a74b-3501f08d9f18)

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Holochain Launcher Version v0.10.0

**Comment by matthme** [comment]
Thank you for the report! Is this when using the `.AppImage` or after installing via `.deb` file?

**Comment by TechSupport26** [comment]
Using the .AppImage

**Comment by matthme** [comment]
Thank you! I made an attempt to fix it (ff6d8bea7787f8c755eaed0b6f704720ed52cdec), I hope the next release fixes it.

**Comment by TechSupport26** [comment]
Awesome. Thanks. 😁

**Comment by matthme** [comment]
This one should also have made it into the latest releases...is the icon still fuzzy for you? If yes I need to investigate further.

**Comment by TechSupport26** [comment]
> is the icon still fuzzy for you?

It is looking much better now.
Thanks.
