### ISSUE TITLE
localhost refused to connect.

### ISSUE THREAD

**Issue by asadiki** [holochain/launcher-tauri#18]
On Windows 10, After clicking the open button in the Holochain Launcher Holochain Launcher v0.3.2
Holochain v0.0.108, I get redirected to Chrome, with the following message:
http://localhost:16684/
This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by guillemcordoba** [comment]
Thanks @asadiki  , can you confirm that this is solved with [Launcher 0.3.3](https://github.com/holochain/launcher/releases/tag/v0.3.3)?

**Comment by asadiki** [comment]
It' solved with 0.3.3
Thanks
