### ISSUE TITLE
Websocket url not replaced with latest client (type mismatch)

### ISSUE THREAD

**Issue by mattyg** [holochain/launcher-tauri#183]
**Describe the bug**
Not sure if this requires a change in hc_launch or in @holochain/client, or both.

On the latest @holochain/client for 0.2.1, `AppAgentWebsocket.connect` takes a `URL` as its first parameter. In previous versions this was a string. To run your happ in hc_launch you would leave the string empty and it injects the websocket url for you.

Now, leaving the URL string empty throw an error. Putting an empty string as the first parameter throws a type error.

My current workaround is this:
```
    const client = await AppAgentWebsocket.connect(
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      //@ts-ignore
      ""
      "my-app"
    );
```

**Comment by matthme** [comment]
That's just a breaking change in the js client that's now expecting a URL object there, see [this](https://github.com/holochain/scaffolding/blob/dfac899a30e015a998c5e896cfd3552c050e95ae/templates/lit/web-app/ui/src/holochain-app.ts.hbs#L23) line in the updated scaffolding tool for how to do it now.
