### ISSUE TITLE
MacOS app doesn't close when you close all the windows

### ISSUE THREAD

**Issue by Connoropolous** [holochain/launcher-tauri#2]
https://github.com/holochain/launcher/blob/720823ed8c7752e42d6376c4c396bfcca65aa5f9/src-tauri/src/main.rs#L50

typical of Mac not to, but doesn't feel right, when you click in the tray icon and say 'Quit' and it doesn't close the app completely from your application bar

**Comment by guillemcordoba** [comment]
Mmmm I don't understand exactly...

When you click quit, does it kill the holochain process? What happens exactly?

**Comment by Connoropolous** [comment]
so all of the windows close, but the application icon remains open with the indicator under it that suggests that the core processes are still running

sample
<img width="60" alt="Screen Shot 2021-07-20 at 2 42 49 PM" src="https://user-images.githubusercontent.com/1409121/126399329-3fe9781a-7f5f-49f7-8fff-6b48feacd5e9.png">

Then you have to right click it as well, and say 'Quit'

**Comment by guillemcordoba** [comment]
Ah mmm okey... So actually that's the intended behavior in a way, you don't need to have the admin window open to have the conductor running in the background. Is that application icon on the system tray, or on the dock on the bottom of the screen?

**Comment by Connoropolous** [comment]
So this is the one on the bottom of the screen. The part you mentioned works fine

**Comment by guillemcordoba** [comment]
Ohhh I know what happens I think... Thanks

**Comment by guillemcordoba** [comment]
@Connoropolous can you confirm that this error is gone with https://github.com/holochain/launcher/releases/tag/v0.2.0?

**Comment by Connoropolous** [comment]
I can confirm!

If sharing this widely, and looking for MacOS adoption, I recommend keeping this instruction for each release, cause there's little to no likelihood folks will look at other released versions release notes:

MacOS
- Download the .dmg, open it, and drag the application to your Applications folder.
- Go to your applications folder, and (important!) right click on it, and click open. Click 'Open' when it gives you a warning about 'Unidentified Developer'.

**Comment by guillemcordoba** [comment]
Thanks!!
