### ISSUE TITLE
Log File Almost 15 GB

### ISSUE THREAD

**Issue by tanerkandemir** [holochain/launcher-tauri#20]
**Describe the bug**

**To Reproduce**
1. Go to 'Holochain Admin Screen'
2. Click on 'Settings > Open Logs'
3. See launcher.log files size almost 15 GB. Just 2 days passed from installation. 

**Logs**
Log file don't open. File size is so much.

**Screenshots**
![image](https://user-images.githubusercontent.com/15521813/136154859-8c4136b8-b45c-4107-8099-c67d5c3c5f43.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H1
 - Holochain Launcher Version v0.3.2

**Comment by guillemcordoba** [comment]
Thanks @tanerkandemir , can you confirm that this is solved with [Launcher 0.3.3](https://github.com/holochain/launcher/releases/tag/v0.3.3)?

**Comment by tanerkandemir** [comment]
4 hours passed for installing v0.3.3. Log file size almost 10 MB. Is it normal @guillemcordoba ?

**Comment by guillemcordoba** [comment]
@tanerkandemir for now I think it is... In following versions we'll keep reducing unnecessary logs.
