### ISSUE TITLE
appstore

### ISSUE THREAD

**Issue by philosnk** [holochain/launcher-tauri#214]
the launcher starts but the apps can't connect.

Holochain Version:
0.1.6-Beta
happ Version:
048f0e820f1049f2c4a72c8bebde51460cabd947
UI Version:
048f0e820f1049f2c4a72c8bebde51460cabd947

Name:appstore
Dna Hash:
uhC0k3YVpx3dcW4B43GqvJoxHH-g86Jai54wZqurROLjssHLw1PsZ
Copy Dna Hash
Network Seed:
launcher
Copy Network Seed
Active Peer Synchronization:
incoming:
no ongoing peer synchronization

**Comment by matthme** [comment]
I assume you're referring to not being able to dowload apps from the App Store? We had problems with our always-online nodes up until today so there were often no nodes available to download the apps from. But that should be fixed now so I'm closing the issue. But if you're still encountering troubles or I misunderstood your issue feel free to re-open it.

**Comment by philosnk** [comment]
Thanks for your answer. evrything works fine now.

**Comment by matthme** [comment]
Glad to hear and thank you for the feedbak!
