### ISSUE TITLE
UI not displaying on Mac OS 10.13.6

### ISSUE THREAD

**Issue by Kasimirsuterwinter** [holochain/launcher-tauri#24]
**Describe the bug**
When i launch the app it opens a window which is white for a second and then turns light grey. I cannot see any buttons on it and in the top menu under Holochain Launcher there is no drop down or Help menu. 

I can see in my activity monitor that the Holochain, Holochain Launcher, Holochain Launcher Network and Tauri are running. 

**To Reproduce**
1. Using a Macbook Pro 15inch 2013 running Mac OS High Sierra 10.13.6
2. Download Holochain Launcher v0.3.4 (Holochain v0.0.109+)
3. Double click on the launcher and drag the Holochain Launcher icon into the Applications folder
4. Right click Holochain Launcher in the applications folder and select Open
5. When prompted with the unidentified developer message click Open. 

**Expected behavior**
The window of the Holochain Launcher will open with a brief moment of white before turning to light grey and then stay this way displaying no buttons. The menu bar will display the Holochain Launcher name but without a drop down and without a Help option next to it. 

**Logs**
I cannot see any option to view logs as there is no menu drop down. 

**Screenshots**

<img width="1001" alt="Screen Shot 2021-10-11 at 00 41 59" src="https://user-images.githubusercontent.com/7826171/136715254-02328fdf-939d-439b-ba24-4dce6fb654eb.png">

**Desktop (please complete the following information):**
 - OS: MacOs v10.13.6
 - Holochain Launcher Version v0.3.4

**Comment by matthme** [comment]
I'm closing this because it refers to an outdated Launcher version.
