### ISSUE TITLE
Holochain Launcher errorwhen starting up

### ISSUE THREAD

**Issue by tatssato** [holochain/launcher-tauri#25]
**Describe the bug**
When I start the launcher on windows, the holochain icon appears twice on the systray and I get the error pasted as a screenshot  below

**To Reproduce**
1. Install launcher
2. double click launcher to open 
3. See screenshot

**Expected behavior**
For Holochain launcher to open with no error.

**Logs**
[launcher.log](https://github.com/holochain/launcher/files/7335141/launcher.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/58587369/137072893-dafedb64-d4cf-42a9-b586-49b5fd8c1009.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Holochain Launcher Version 0.3.4

**Comment by guillemcordoba** [comment]
Mmm @tatssato could you say a bit more about this Windows system? Is it 32 bits?

**Comment by guillemcordoba** [comment]
@tatssato can you install WebView https://developer.microsoft.com/en-us/microsoft-edge/webview2/ and try again?

**Comment by matthme** [comment]
I'm closing this because it refers to an outdated version of the Launcher.
