### ISSUE TITLE
Clicking 'open' on an installed webhapp opens up Firefox, not the system-wide default browser

### ISSUE THREAD

**Issue by bierlingm** [holochain/launcher-tauri#26]
**Describe the bug**
Clicking 'open' on an installed webhapp opens up Firefox, not the system-wide default browser

**To Reproduce**
1. Go to your launcher
2. Click on 'OPEN' on an installed webhapp
3. Watch FireFox being opened

**Expected behavior**
I would expect the open button to open the localhost instance in the system-wide default browser set by the user.

**Logs**
/

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS: macOS 12.0 Beta (21A5543b)
 - Holochain Launcher: v0.3.2
 - Holochain: v0.0.108
 - Lair Keystore: v0.0.4

**Additional context**
/

**Comment by matthme** [comment]
I'm closing this because apps are not opened in the browser anymore with the latest Launcher versions.
