### ISSUE TITLE
Unable to Install on Kali Linux 2021.3

### ISSUE THREAD

**Issue by its0din-ai** [holochain/launcher-tauri#28]
Downloading the deb package, and do some dpkg install.
and it say **Package libappindicator3-1 is not installed.**

and I found this https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037
the libappindicator is Deprecated

the problem is I can't install the LibAppIndicator3-1

**Comment by guillemcordoba** [comment]
Thanks @its0din-ai ! I've created an issue upstream to Tauri: https://github.com/tauri-apps/tauri/issues/2799. Let's see if we can get it fixed.
