### ISSUE TITLE
Add AUR info to install instructions

### ISSUE THREAD

**Issue by robot5x** [holochain/launcher-tauri#30]
Hi -

can you please consider adding Archlinux AUR instructions for install of holochain-launcher.

For any pacman-based system, user can simply go to https://aur.archlinux.org/packages/holochain-launcher/ and download the tarball to build and install the package with pacman - or with yay. This is a bit nicer and cleaner than using AppImage for non-apt distros.

Thank you!

**Comment by guillemcordoba** [comment]
Thanks @robot5x! Do you think it's enough [like this](https://github.com/holochain/launcher/releases/tag/v0.3.4)?

**Comment by robot5x** [comment]
yes it's fine! thanks a lot Guillem
