### ISSUE TITLE
Conductor keeps timing out on start up on Kizuna happ

### ISSUE THREAD

**Issue by tatssato** [holochain/launcher-tauri#31]
**Describe the bug**
Conductor keeps timing out when the kizuna happ is launched.
I see `[2021-10-20T00:33:09.133353500+02:00] INFO - [HOLOCHAIN] [2mOct 20 00:33:09.133[0m [33m WARN[0m kitsune_p2p::gossip::sharded_gossip: Overloaded with incoming gossip.. 30 messages` a lot in the launcher log as well
more info [here](https://github.com/hc-institute-japan/kizuna/issues/102)

**To Reproduce**

**Expected behavior**

**Logs**
Please attach here the `launcher.log` file. To find it, go to `Holochain Admin` window of the Holochain Launcher, select the  `Settings` menu, and select `Open Logs`. Attach that file to this issue.
[launcher (2).log](https://github.com/holochain/launcher/files/7378017/launcher.2.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/58587369/138025386-ad4568f6-3eb2-4324-ba76-abde27f32e87.png)
![image](https://user-images.githubusercontent.com/58587369/138025486-28534cd7-fae7-4eb6-a412-d1c569a99324.png)

**Desktop (please complete the following information):**
 - Holochain Launcher Version 0.3.4

**Additional context**

**Comment by abe-njama** [comment]
@tatssato are you still experiencing this issue? I'm unable to replicate the problem since I'm encountering another issue where Kizuna shows as paused on Launcher, but this is being looked into already.

**Comment by abe-njama** [comment]
@tatssato I've been able to successfully launch Kizuna, register my nickname and log in. I suppose this is no longer an issue. 
![image](https://user-images.githubusercontent.com/62102332/148843307-ce71055f-057a-49fd-b020-b4a99a3b8ce1.png)

**Comment by matthme** [comment]
I'm closing this because it refers to outdated Launcher and Holochain versions.
