### ISSUE TITLE
Infinite loading time with both Elemental Chat and Chess

### ISSUE THREAD

**Issue by Dahriim** [holochain/launcher-tauri#33]
I'm on Mac OS and I followed all the instructions, gave the authorization to the Launcher from my firewall to allow internet connection but:
1.   Elemental Chat is stuck on the main page with a message saying that it's trying to connect, but keeps trying with no success every 15 seconds
2.   Elemental Chess is not even opening a main page, just a blank localhost page with at the center a never ending loading wheel.
3.   Sometimes the Holochain Launcher icon is not appearing in the upper bar, so there is no way to access the admin page nor defenetly quitting from the launcher. In that case I couldn't access the admin page without restarting my pc. 

Maybe I'm doing some mistake myself, but after 5 hours of attempts I couldn't try one of the three happs I downloaded (also had a bug with Kizuna where I couldn't register my Nickname). 

Thank you for your work!

**Comment by guillemcordoba** [comment]
Hi! Thanks for putting out an issue! This is the kind of feedback we need at this moment.

So our seems there is a problem when the apps try to connect to holochain, but I need the logs to know what's happening. Could you go to settings > open logs and attach them here?

**Comment by Dahriim** [comment]
Unfortunately it seems I have no settings option in my Holochain Launcher admin page, I will attach a picture of the main page so you can tell if something is off.
![163558731733716184172218598145](https://user-images.githubusercontent.com/93393186/139528226-fc4d5873-fe98-4d41-8818-fc0edbd9d27b.jpg)

**Comment by Dahriim** [comment]
[launcher.log](https://github.com/holochain/launcher/files/7446245/launcher.log)
