### ISSUE TITLE
[macOS] "Quit" from system bar icon only closes launcher window

### ISSUE THREAD

**Issue by jost-s** [holochain/launcher-tauri#4]
Perhaps this is linked to issue #2:
When I select "Quit" from the system bar's icon, only the the launcher window is closed. Clicking it again does nothing.
![image](https://user-images.githubusercontent.com/28270981/126873938-65410c59-e940-4ed7-8e96-9672d194753a.png)

**Comment by guillemcordoba** [comment]
Mmm so the systray icon persists?

**Comment by jost-s** [comment]
Yes, correct

**Comment by guillemcordoba** [comment]
@jost-s can you confirm that the error is gone with https://github.com/holochain/launcher/releases/tag/v0.2.0?

**Comment by jost-s** [comment]
@guillemcordoba Confirmed that it quits correctly 💯
