### ISSUE TITLE
Useful to have associated HDK version for Holochain version in the Launcher Release Changelog

### ISSUE THREAD

**Issue by Connoropolous** [holochain/launcher-tauri#45]
I propose this because often times happs are being related using the HDK version they're built for, specified, versus the holochain version, and these versions can be out of sync. 

The only way that people can find this information easily is by going here: https://github.com/holochain/holochain/blob/main/CHANGELOG.md
But most people wouldn't know that.

**Comment by Connoropolous** [comment]
Referring to:

<img width="400" alt="Screen Shot 2022-03-20 at 2 47 06 PM" src="https://user-images.githubusercontent.com/1409121/159187318-01e21583-fd93-4a15-a151-ab07c9493d78.png">

**Comment by guillemcordoba** [comment]
Thanks :)

**Comment by matthme** [comment]
This has become common practice in the meantime so I'll close it now. Reopen if you think it's not clear enough in the release notes.
