### ISSUE TITLE
switch to AppBundleSource::Path variant for install_happ to install bigger happs

### ISSUE THREAD

**Issue by Connoropolous** [holochain/launcher-tauri#46]
If the referenced LOC used Path instead of Bundle it would be able to handle happ bundles which exceed 16 mb which can easily happen. In fact it has happened already with holo-rea which led to us using the sub optimal approach of referencing dna files by Url for download, breaking the distributed pattern. 

https://github.com/holochain/launcher/blob/2ca0edc6c24023ec9209c3dac44d115816a4500b/src-tauri/src/commands/install_app.rs#L98

**Comment by guillemcordoba** [comment]
This should be working as per Launcher 0.4.3.

**Comment by Connoropolous** [comment]
Awesome thanks. Its actually a big deal
