### ISSUE TITLE
Happ ordering non-deterministic

### ISSUE THREAD

**Issue by zippy** [holochain/launcher-tauri#50]
**Describe the bug**
Every time you restart the launcher the hApps will be listed in a different order

**To Reproduce**
1. Add a bunch of happs
2. look at the order
3. Restart the launcher
4. See a different order because different holochain versions are listed in different orders 

**Expected behavior**
I think the holochain versions should allways be the same order, probably most recent to oldest.  Additionally the order in the menu seems to match the order on the screen including with spaces.  It seems to me that the order in the menu should be pure alphabetical, not grouped by Holochain version.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Holochain Launcher Version 0.4.6
 
**Additional context**

**Comment by matthme** [comment]
Fixed by #62
