### ISSUE TITLE
Conductor config can be easily overwritten when using a custom holochain binary

### ISSUE THREAD

**Issue by maackle** [holochain/launcher-tauri#52]
**Describe the bug**

When using a custom holochain binary of a version unsupported by the launcher,
when I edit a field in the conductor-config.yaml which is not recognized by by the latest version recognized by the launcher,
that field will be ignored and deleted the next time the launcher restarts,
because it attempts to deserialize the config into a `ConductorConfig` which does not contain that field.

**To Reproduce**
1. Set up a custom holochain binary via the Configuration menu item
2. Install an app into the custom conductor, and run it
3. Exit the launcher
4. Add some unrecognized field to the config, e.g. append `hello: hi` to `$HOME/.config/holochain/custom/conductor-config.yaml`
5. Restart the launcher, and watch your field get clobbered

**Expected behavior**

I expect the config to remain the same when the launcher restarts, even if the config is invalid. This is particularly important for `tuning_params`, which are expected to change often, since we add new ones all the time for debugging and diagnostic purposes, which is an especially useful usecase for custom binaries in the launcher. 

I think it would be more appropriate to not deserialize the config into the `ConductorConfig` struct, and instead work with the raw structured YAML to edit the admin port as needed, to fully preserve the rest of the config.

**Logs**

No relevant logs.

**Comment by guillemcordoba** [comment]
Ah... Really nice, you got to the root cause of it. 

Yes your proposed solution makes sense. How important/urgent is this?

**Comment by maackle** [comment]
@guillemcordoba I am hoping to do some live testing with some folks using the launcher tomorrow, and we need to use custom config for that. I can try a PR.
