### ISSUE TITLE
Make the passphrase input box focused on app startup

### ISSUE THREAD

**Issue by maackle** [holochain/launcher-tauri#53]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to immediately type my passphrase when opening Launcher, instead of having to click the box first.

**Describe the solution you'd like**
Make the passphrase input box focused on app startup

**Comment by guillemcordoba** [comment]
Yes makes a lot of sense. Thanks!

**Comment by matthme** [comment]
Is fixed by 8f34309584094c61d777bad74741273ec7236728.
