### ISSUE TITLE
Cannot install hApps: The node Cert has timed out their gossip round

### ISSUE THREAD

**Issue by dcts** [holochain/launcher-tauri#54]
**Describe the bug**
I cannot install elemental chess hApp (or any other hApp). 

**To Reproduce**
1. I had an old version of the launcher, I uninstalled it first.
2. Installed launcher v0.4.7
3. Did factory reset
4. Created a new password
5. Restarted the launcher and entered my newly created password
6. Tried to install elemental chess or any other app.

**Expected behavior**
Elemental Chess being installed.

**Logs**
[launcher.log](https://github.com/holochain/launcher/files/8806796/launcher.log)

**Screenshots**
![Bildschirmfoto vom 2022-05-31 17-40-28](https://user-images.githubusercontent.com/44790691/171217274-968cc330-4c57-49b3-a704-eddb15a2f7de.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Holochain Launcher Version: 0.4.7

**Additional context**
There were 3 crashreports created, since I cannot upload them here (toml not supported) I did sent them to devcore@holochain.org.

**Comment by dcts** [comment]
After researching a bit more I found that issue #48, might be related. 

Waited for some time and was now able to install the Notebooks hApp. But elemental chat still fails to instal. Will try later and in case it succeeds report here :)

**Comment by dcts** [comment]
Installing elemental chess now worked for me :) 

Just curious if this is correct: my launcher requested the elemental chess DNA but either (a) no user was online or (b) all users that were online did not have the required DNA file (because they did not install elemental chess themselves)?

**Comment by guillemcordoba** [comment]
Cool!

So actually no... We have a couple of always online nodes that make sure that there are always nodes in the DHT. The issue is that the files are big entries which take some time to gossip, and right now the gossip algorithm is limited: each node assumes that they are already holding all the data.

There is a new algorithm in the works, which should solve this.
