### ISSUE TITLE
error: `App download failed. Please try again later.`

### ISSUE THREAD

**Issue by mhuesch** [holochain/launcher-tauri#57]
**Describe the bug**

on macOS, I installed the `.dmg` from https://github.com/holochain/launcher/releases/tag/v0.4.10. I initialized the keystore with a password, then tried to install an app (tried both Notebooks and We).

for both, the installation failed with the message `App download failed. Please try again later.`

**To Reproduce**

see above.

**Expected behavior**

I would expect the app to be installed. or for more intelligible error output to be provided.

**Logs**

[launcher.log](https://github.com/holochain/launcher/files/9270657/launcher.log)

**Screenshots**

n/a

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.3.1
 - Holochain Launcher Version: v0.4.10

**Comment by mhuesch** [comment]
I just tried on Launcher version v0.4.9 and observe the same error 🤔

**Comment by guillemcordoba** [comment]
Did it work for you in v0.4.9 before?

**Comment by mhuesch** [comment]
@guillemcordoba sorry, probably confusing wording.

no, I had not ever tried before today. I tried 0.4.10 & encountered the failure. then I tried 0.4.9 & also encountered the failure.

**Comment by guillemcordoba** [comment]
Okey cool, thanks. This should be one of two things: 

1) The gossiping of the files taking a long time (I've seen it take hours and even a couple of days).
2) There is no node online right now that has the contents of the files to gossip them to you.

I'm going to bring up an always online node for the devhub to at least amend nº 2. I'll ping you when that's done.

**Comment by guillemcordoba** [comment]
Done! I've brought up an always online node. Can you try again within some minutes? Restarting the launcher sometimes helps.

**Comment by mhuesch** [comment]
thanks! Sid and I just tested and we were able to sync up, create a We, and install both notes+calendar applets into it.

closing 🙏

**Comment by gcassel** [comment]
I've had a similar problem for over 24 hours since downloading Launcher 4.10 , on Windows 10 in my case.  However, I note your comment above @guillemcordoba : "The gossiping of the files taking a long time (I've seen it take hours and even a couple of days)" -- so, I'll keep on checking.

**Comment by gcassel** [comment]
Hey, I'm good now; *We* installed a couple of hours later :)
