### ISSUE TITLE
Caddy stopped working

### ISSUE THREAD

**Issue by tatssato** [holochain/launcher-tauri#6]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
Please attach here the `launcher.log` file. To find it, go to `Holochain Admin` window of the Holochain Launcher, select the  `Settings` menu, and select `Open Logs`. Attach that file to this issue.
[launcher.log](https://github.com/holochain/launcher/files/7243175/launcher.log)

> In Ubuntu, there is a weird error that prevents the upload of a file from inside a hidden folder. To work around it, you can copy the `launcher.log` file to another non-hidden location, and upload it from there.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOs v10.13]
 - Holochain Launcher Version [e.g. 0.], you can find out in `Help` > 'About'

**Additional context**

**Comment by tatssato** [comment]
[launcher.log](https://github.com/holochain/launcher/files/7243279/launcher.log)

**Comment by guillemcordoba** [comment]
Yep thanks, unfortunately I didn't pipe appropriate the caddy logs to see the error... I'm preparing a new build that has them enabled.

**Comment by guillemcordoba** [comment]
I'm going to close this for now since the Caddy logs have been piped and various caddy bugs were fixed on new versions. Re-open if it happens again.
