### ISSUE TITLE
Create sign_zome_call_request command

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/launcher-tauri#67]
Coupled with https://github.com/holochain/holochain-client-js/issues/130

**Comment by Connoropolous** [comment]
I saw a little diagram of this flow somewhere... is anyone tracking the question of just how inefficient this is going to be? it looks like per 1 zome call it's another additional whole round trip. Sounds super performance costly. 

What about client side signing, like doing with Holo?

**Comment by jost-s** [comment]
Thanks for raising that concern, @Connoropolous. We should take that into consideration indeed. There'll be client side signing for apps outside of the launcher, but the launcher deserves another look too.

Actually which diagram are you talking about? In the last version I saw there's not another round trip to the conductor for signing, but a call to Lair. Is that what you mean?

**Comment by Connoropolous** [comment]
Yeah, this one:
https://github.com/holochain/launcher/blob/main/docs/architecture.md#signing-a-zome-call

I guess its not two round trips to the conductor, one is just to lair, which seems like it could be much more performant

**Comment by matthme** [comment]
Just to note, calls to the lair keystore happen via [IPC](https://tauri.app/v1/references/architecture/inter-process-communication/).

**Comment by jost-s** [comment]
And they'll always be on the same machine when using the Launcher.

**Comment by matthme** [comment]
Merged in with https://github.com/holochain/launcher/pull/110
