### ISSUE TITLE
UI is blank, only menu bar is interactive (.AppImage)

### ISSUE THREAD

**Issue by rbnmf** [holochain/launcher-tauri#7]
**Describe the bug**
UI is unavailable (except the menu bar). The whole screen is blank. Also, the option Help > Version does nothing.

**To Reproduce**
1. Launch app

**Expected behavior**
Ability to perform any action (besides using the menu bar).

**Logs**
[launcher.log](https://github.com/holochain/launcher/files/7244405/launcher.log)

**Screenshots**

![Screenshot from 2021-09-28 15-32-10](https://user-images.githubusercontent.com/31513406/135097662-3689b15d-a79d-4567-98a3-497575188511.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.03 LTS 64-bit
 - DE: GNOME 3.36.8
 - Windowing System: X11
 - Holochain Launcher Version: v.0.3.0 (.AppImage)

**Comment by guillemcordoba** [comment]
@rubenmantecon by the logs, it seems you have booted up the launcher twice... Can you reboot and try again, and see if that fixes it?

**Comment by rbnmf** [comment]
@guillemcordoba I'm afraid that rebooting does not solve the issue. The problem remains. On the .deb version this would have solved the problem, but doesn't seem to be the case for the .AppImage version.

**Comment by guillemcordoba** [comment]
@rubenmantecon Can you confirm [0.3.1](https://github.com/holochain/launcher/releases/tag/v0.3.1) fixes the issue?

**Comment by rbnmf** [comment]
Yes, see #9
