### ISSUE TITLE
Feature request: show me storage space used by Holochain Launcher

### ISSUE THREAD

**Issue by Connoropolous** [holochain/launcher-tauri#77]
I often run really close to the wire in terms of storage space on my computer, and since I almost just ran out again I found myself wondering how much space Launcher and the installed apps were taking up. As I understand it since we have DevHub installed automatically, it could be a non-negligible amount of space. So just a quick and easy way to see how much

**Comment by matthme** [comment]
Yes this would definitely be a nice feature. I don't know what this would mean in terms of efforts for making it work across platforms but I'll keep it in mind. Ideally one would see the storage space per app I guess.

**Comment by matthme** [comment]
This has been implemented in the meantime. Maybe it can be extended to app level info once holochain's API provides corresponding information but I'll close it for now.
