### ISSUE TITLE
UI does not load or function Properly

### ISSUE THREAD

**Issue by 0phelia36** [holochain/launcher-tauri#8]
**Describe the bug**
After starting the launcher the UI is blank and buttons do not work, except for the "Report Issue" button.

To Reproduce

    Launch app

Expected behavior
UI to load and function properly

**Logs**
[launcher.log](https://github.com/holochain/launcher/files/7244574/launcher.log)

**Screenshots**

On running the program from the terminal the following errors are returned.
![image](https://user-images.githubusercontent.com/84165411/135101415-8bc02a60-9d01-409e-84d1-314ddc7077bc.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Holochain Launcher Version: v.0.3.0 (.AppImage)

**Additional context**
Different I think from #7 since the "Address already in use" error is not present in the most recent launch but the UI still fails to load properly.

**Comment by guillemcordoba** [comment]
@0phelia36  Can you confirm [0.3.1](https://github.com/holochain/launcher/releases/tag/v0.3.1) fixes the issue?

**Comment by 0phelia36** [comment]
@guillemcordoba 0.3.1 does fix my issue.
