### ISSUE TITLE
Feature request: differentiate custom binary from preinstalled binaries in log

### ISSUE THREAD

**Issue by maackle** [holochain/launcher-tauri#80]
**Is your feature request related to a problem? Please describe.**
When using a custom binary which is tagged as the same version as one of the existing Launcher binaries, I cannot differentiate the two binaries. For instance:

```
[2022-09-20T12:20:14.595913064-07:00] INFO - [HOLOCHAIN v0.0.162] ...
```

I can't tell if this is the preinstalled v0.0.162 release, or the custom build I created from `develop` based on that same version number

**Describe the solution you'd like**
I'd like some kind of differentiation between the custom binary and other versions. Perhaps `[HOLOCHAIN Custom]`?

**Describe alternatives you've considered**

**Additional context**
I'm not sure how a `HolochainVersion` is assigned to the case of using a custom binary, but it seems like custom binaries are not accounted for, and `HolochainVersion` is what specifies the string I'm talking about. Mainly here: https://github.com/holochain/launcher/blob/1d61567c77893dc3ec3e2c51404ed596524da2ce/crates/holochain_manager/src/launch.rs#L56

**Comment by matthme** [comment]
Thank you! bfba0a16b121ea72a571bd3862120c4897b4b1c4 fixes this. A new release is on its way.
