### ISSUE TITLE
[BUG] Can't install an app that requires a membrane proof

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/launcher-tauri#86]
**Describe the bug**

An error shows up trying to install an app:

![image](https://user-images.githubusercontent.com/2046932/194710049-fab6c746-d2c4-413d-aa80-d85a5cd94e97.png)

Seems to be related to a bad argument type passed [here](https://github.com/holochain/launcher/blob/f24cc42a256e0a6196f0a6c2b894cbffae1917ef/src/components/InstallAppDialog.vue#L381).

**To Reproduce**

1. Download this [happ](https://holo-host.github.io/holo-hosting-app-rsm/releases/downloads/core-app/0_3_3_alpha1/core-app.0_3_3_alpha1.happ).
2. Try to install it from the filesystem in the launcher, setting some random value in the membrane proof textfield.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOs v10.13]
 - Holochain Launcher Version: hc 0.0.162 launcher v0.6.1.

**Comment by matthme** [comment]
Should be fixed with a6c092df871b76bd59b42e74b8c5065a8fec930d, so I'm closing it. Although the question about the right UX for membrane proofs in general remains open.
