### ISSUE TITLE
Entering a password to a second window does not give an error.

### ISSUE THREAD

**Issue by TechSupport26** [holochain/launcher-tauri#88]
**Describe the bug**
When 2 instances of the launcher are running and the second one is not given a password (Leave it blank and hit enter) it will never give an error and will use a lot of CPU until you close the launcher.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the launcher and enter your password.
2. Once it has loaded open a new instance and enter any characters.
3. The launcher never gives an error and uses a lot of CPU.

**Expected behaviour**
The "Invalid password" message should be displayed and the password box reset so you can try entering another password.

**Logs**
[launcher.log](https://github.com/holochain/launcher/files/9793497/launcher.log)

**Screenshots**

https://user-images.githubusercontent.com/65631811/196014880-fd2914ab-7d9a-4261-959c-8b77bfaa137b.mp4

**Desktop (please complete the following information):**
 - OS: Edition	Windows 10 Pro
Version	21H2
Installed on	‎19/‎04/‎2021
OS build	19044.2130
Experience	Windows Feature Experience Pack 120.2212.4180.0
 - Holochain Launcher Version 0.7.0

**Additional context**
The UI is getting better and better and thanks for the releases :)

**Comment by matthme** [comment]
Interesting. It's not even supposed to be possible to run two instances of the launcher alongside each other, it's supposed to throw an error before you even get to the password screen. I have to figure out what's going on there...
Thanks for raising the issue!

**Comment by matthme** [comment]
For documentation: Part of the issue seems to be a bug/limitation in a crate we are using: https://github.com/GuillaumeGomez/sysinfo/issues/860 which affects [this](https://github.com/holochain/launcher/blob/a6c092df871b76bd59b42e74b8c5065a8fec930d/src-tauri/src/launcher/manager.rs#L474) line in our code.

**Comment by TechSupport26** [comment]
It looks like this is fixed since version 0.9.4 with the launcher recognising that the same process is already in use. (That is my understanding) so feel free to close this.
Also, I am now running Linux but I don't think that matters in this case.

Perhaps adding something to say the launcher may already be running. However, in saying that, following the instructions provided will quit the open launcher and resolve the issue anyway.

**Comment by matthme** [comment]
It was actually still present on Windows but it has been addressed by using `tauri-plugin-single-instance` (69372b2). If there is already an instance running it will open the existing instance, except the new instance is explicitly started with a custom profile.
