### ISSUE TITLE
App crashes after second startup, possibly due to 'address already in use' (.deb)

### ISSUE THREAD

**Issue by rbnmf** [holochain/launcher-tauri#9]
**Describe the bug**
When running the app for the first time, it launches. After closing it, if one tries to launch it again, it crashes.

**To Reproduce**
1. Launch app from app menu, or use `holochain-launcher` on a terminal
2. Close via GUI
3. [If launched via terminal] ctrl+c the terminal process
4. Repeat step 1

**Expected behavior**
App booting for a second time.

**Logs**
[launcher.log](https://github.com/holochain/launcher/files/7244707/launcher.log)

**Desktop**
 - OS: Ubuntu 20.04.03 LTS 64-bit
 - DE: GNOME 3.36.8
 - Windowing System: X11
 - Holochain Launcher Version: v.0.3.0 (.deb)

**Comment by rbnmf** [comment]
**Workaround**
```
ps aux | grep holochain
kill -9 <process name(s)>
```

Then start again normally

**Comment by guillemcordoba** [comment]
@rubenmantecon can you confirm that [0.3.1](https://github.com/holochain/launcher/releases/tag/v0.3.1) fixes this issue?

**Comment by rbnmf** [comment]
It does. Note that this solution relies on using the systray, which would need to enabled via the [TopIcons](https://extensions.gnome.org/extension/1031/topicons/) extensions or similar.
